### ISSUE TITLE
rdm_mbw_mr - srun timeout

### ISSUE THREAD

**Issue by a-abraham** [ofi-cray/cray-tests#32]
Since the amount of data sent across in the rdm_mbw_mr tests has increased significantly the current timeout set in **run_cray_tests.py** for **rdm_mbw_mr** is too short, causing srun to terminate the test.

An appropriate time out needs to be determined to allow for the length of the test - or the amount of data sent must be decreased.

**Comment by a-abraham** [comment]
FYI
-t00:06:00   Failed
-t00:06:30   Succeeded 
-t00:07:00   Succeeded

@e-harvey @sungeunchoi

**Comment by sungeunchoi** [comment]
Do you know which processor types you ran on?  In any case, let's round it up to 10 minutes, since in our jenkins testing we'll probably get some random mix.

**Comment by a-abraham** [comment]
I don't know sorry - do you typically specify that with an srun flag? 

ct_default_timeout = 60  currently sets the timeout for all the tests. 
If I set this to 600, that will set the default timeout for all the tests to 10 minutes. Is that what is desired or do we want to limit it specifically to the rdm_mbw_mr test?

**Comment by sungeunchoi** [comment]
No worries.  You can use an srun flag, but we don't generally do that for jenkins testing.

This is a bit more work, but what I think should be done is to add the timeout to the list of test parameters in `testlist`.  In other words, remove it as a argument to the script and add `'timeout=600'` to rdm_mbw_mr's record in `testlist`.  Also, if a `timeout` field is not specified in the `testlist`, use `ct_default_timeout` when creating the `craytests` object.
