### ISSUE TITLE
Add RA-like performance test

### ISSUE THREAD

**Issue by sungeunchoi** [ofi-cray/cray-tests#34]
To simulate PGAS applications

**Comment by jswaro** [comment]
RA-like?

**Comment by sungeunchoi** [comment]
Random Access.  We talked about this a couple weeks ago.

**Comment by jswaro** [comment]
Refresh my memory on this? I've been working on other projects more heavily lately.

**Comment by sungeunchoi** [comment]
@hppritcha Was the version from the OpenSHMEM paper ever committed anywhere?  That would be a good reference implementation.

**Comment by jswaro** [comment]
I'm not certain I see the purpose behind this type of test yet. What prevents us from downloading and using the HPCC random access suite with OpenMPI rather than creating our own RA/GUPS test?

**Comment by sungeunchoi** [comment]
Nothing prevents us from doing that.  We talked about doing this to mimic a well known communication pattern for the PGAS space.  Having a libfabric version gets other software out of the way when looking at the GNI provider performance, which is what we want to do.  This version would also be valuable for the implementers of libraries/languages on top of libfabric to make sure that they are doing the best they can for their versions.  Obviously this is a secondary concern, but to me it's important because it helps our users.

**Comment by jswaro** [comment]
Seems like we should either do a lite version of this, or port the existing HPCC RA code to libfabrics. Which is the preference here?

**Comment by sungeunchoi** [comment]
I don't know what you mean by "lite" version, but I'd take a look at the SHMEM or Chapel versions of HPCC RA.  IMO they use more natural mappings of the communication pattern (which makes sense since this is really a PGAS benchmark).  Either using one-sided or atomics (or both) would be preferable to using send/recv.

**Comment by jswaro** [comment]
By 'lite', I mean a trimmed down version of the test that only exercises a subset of the functionality of the original test, perhaps even with methods that are not as complex as the original test.

**Comment by sungeunchoi** [comment]
Hmm... RA is not exactly complicated, so what specifically do you mean?

**Comment by jswaro** [comment]
Do we want to copy the tests verbatim with minimal changes, or do we want to do a simplified version of them? Some of the calculations that I saw in the source was fairly complicated. Perhaps this is significantly different from the chapel or shmem versions.

**Comment by sungeunchoi** [comment]
Which version are you looking at?  IIRC the HPCC reference version included a RNG, but other than that did nothing too complicated: compute table, distribute table, do updates, validate updates.
